apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: cinemaabyss
  labels:
    app: event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: ghcr.io/boniffacci/architecture-pro-cinemaabyss/events-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
            - name: KAFKA_BROKER
              value: "kafka:9092"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson

---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: cinemaabyss
spec:
  selector:
    app: event-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
